###############
POST http://127.0.0.1:8000/accounts/register/
Content-Type: application/json
Accept: application/json

{
  "email": "amir@gmail.com",
  "phone_number": "01111111111",
  "full_name": "amir",
  "password": "6541"
}
############################################

############################################
POST http://127.0.0.1:8000/accounts/verify/
Content-Type: application/json
Accept: application/json

{
  "code": 7647
}

################################3
POST http://127.0.0.1:8000/accounts/login/
Content-Type: application/json
Accept: application/json

{
  "phone_number": "09000000000",
  "password":"6541"
}

####
GET http://127.0.0.1:8000/accounts/profile/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3Njc3MTUzLCJpYXQiOjE3NDc2NzExNTMsImp0aSI6Ijk0MDBmODg2NjU0NTRmZTJiYjIzMDNmNDlhNWU2ODliIiwidXNlcl9pZCI6IjA5MDAwMDAwMDAwIiwiaWQiOjEsInBob25lX251bWJlciI6IjA5MDAwMDAwMDAwIiwiZnVsbF9uYW1lIjoibWhtZCIsImVtYWlsIjoibWhtZEBnbWFpbC5jb20ifQ.7GxyBj4Vq-1sSXvBqd9BqtkvELC2udgbX0HT0sFn_5U


####
####
PUT  http://127.0.0.1:8000/accounts/profile/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NDk1OTE0LCJpYXQiOjE3NDc0ODk5MTQsImp0aSI6ImQ2NDcyYmIwMDEyNTQ2MmE4MzUyODUyZTIwYjg5YzFjIiwidXNlcl9pZCI6IjA5MTExMTExMTExIiwiaWQiOjQsInBob25lX251bWJlciI6IjA5MTExMTExMTExIiwiZnVsbF9uYW1lIjoiaGFzYW4iLCJlbWFpbCI6Imhhc2FuQGdtYWlsLmNvbSJ9.Y_uVLEtHzBorQachtjYxK7FVP9AYRztkSvc-OBcf_XM

{
  "full_name": "amir"

  }

####
POST http://77.237.82.221:8000/accounts/register/
Content-Type: application/json
Accept: application/json

{
  "email": "test@gmail.com",
  "phone_number": "09227700896",
  "full_name": "test",
  "password": "6541"
}


########

#######

##########
POST http://77.237.82.221:8000/accounts/login/
Content-Type: application/json
Accept: application/json

{
  "phone_number": "60000000000",
  "password":"6541"
}

###################################
GET  http://127.0.0.1:8000/question-app/integral/1/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3Njc3MTUzLCJpYXQiOjE3NDc2NzExNTMsImp0aSI6Ijk0MDBmODg2NjU0NTRmZTJiYjIzMDNmNDlhNWU2ODliIiwidXNlcl9pZCI6IjA5MDAwMDAwMDAwIiwiaWQiOjEsInBob25lX251bWJlciI6IjA5MDAwMDAwMDAwIiwiZnVsbF9uYW1lIjoibWhtZCIsImVtYWlsIjoibWhtZEBnbWFpbC5jb20ifQ.7GxyBj4Vq-1sSXvBqd9BqtkvELC2udgbX0HT0sFn_5U
####################################################################
POST   http://127.0.0.1:8000/question-app/integral/1/4/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3Njc3MTUzLCJpYXQiOjE3NDc2NzExNTMsImp0aSI6Ijk0MDBmODg2NjU0NTRmZTJiYjIzMDNmNDlhNWU2ODliIiwidXNlcl9pZCI6IjA5MDAwMDAwMDAwIiwiaWQiOjEsInBob25lX251bWJlciI6IjA5MDAwMDAwMDAwIiwiZnVsbF9uYW1lIjoibWhtZCIsImVtYWlsIjoibWhtZEBnbWFpbC5jb20ifQ.7GxyBj4Vq-1sSXvBqd9BqtkvELC2udgbX0HT0sFn_5U

{
  "answer": "1"
}
#################################1-1 2-4 3-2 4-1

GET  http://127.0.0.1:8000/accounts/thruthling/
Content-Type: application/json
Accept: application/json

#################################
GET  http://127.0.0.1:8000/accounts/test/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MzA2NjIxLCJpYXQiOjE3NDYzMDA2MjEsImp0aSI6IjA5OWM4OWE3YzI1NTRlYTFhZTFiZmMxMGJmYjAyMDBjIiwidXNlcl9pZCI6IjYwMDAwMDAwMDAwIiwicGhvbmVfbnVtYmVyIjoiNjAwMDAwMDAwMDAiLCJmdWxsX25hbWUiOiI2IiwiZW1haWwiOiI2QGV4YW1wbGUuY29tIiwic2NvcmUiOjQsImxhc3QtcXVlc3Rpb24taW50ZWdyYWwiOjEsImxhc3QtcXVlc3Rpb24tZGVyaXZhdGl2ZSI6MH0.iCpHVuRm4EevCE2hSkGKsObOSDKQofa4EVggd_SQrzc
####################################
POST http://127.0.0.1:8000/question-app/13/ 
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTA2Mzc3LCJpYXQiOjE3NDQ5MDAzNzcsImp0aSI6IjRiNTc3N2NhNDg0NTQyM2U4YmI3MjFhNmY0YmY0ZjhmIiwidXNlcl9pZCI6IjYwMDAwMDAwMDAwIiwicGhvbmVfbnVtYmVyIjoiNjAwMDAwMDAwMDAiLCJmdWxsX25hbWUiOiI2IiwiZW1haWwiOiI2QGV4YW1wbGUuY29tIiwic2NvcmUiOjIsImxhc3QtcXVlc3Rpb24taW50ZWdyYWwiOjEsImxhc3QtcXVlc3Rpb24tZGVyaXZhdGl2ZSI6MH0.ml9mjJHTuWNTCQ720kVDKB7EzJtWGuK-G-jo5-j01G4
{
  "answer": "1"
}




###################################33

POST http://127.0.0.1:8000/accounts/token/
Content-Type: application/json
Accept: application/json

{
  "email": "7@example.com",
  "password": "6541"
}


######################################

POST http://127.0.0.1:8000/accounts/token/refresh/
Content-Type: application/json
Accept: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTkxOTY1NCwiaWF0IjoxNzQ1MzE0ODU0LCJqdGkiOiJjODQ1M2JmNzQxZDk0NjBlOTVlOTJjOTVkNmNhYmU5ZCIsInVzZXJfaWQiOiI3MDAwMDAwMDAwMCIsInBob25lX251bWJlciI6IjcwMDAwMDAwMDAwIiwiZnVsbF9uYW1lIjoiNyIsImVtYWlsIjoiN0BleGFtcGxlLmNvbSIsInNjb3JlIjowLCJsYXN0LXF1ZXN0aW9uLWludGVncmFsIjowLCJsYXN0LXF1ZXN0aW9uLWRlcml2YXRpdmUiOjB9.8vRXhW923J-72gODeo2YJTYHaUM6nJy3IUdCP5Y7gTA"
}



#########################################
GET http://127.0.0.1:8000/accounts/test/

Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MzA3MDUyLCJpYXQiOjE3NDYzMDEwNTIsImp0aSI6ImUzYWY1ZmIwNjFmZDQ0NGQ5NDM1MzU0MWJhN2Q0YzNmIiwidXNlcl9pZCI6IjYwMDAwMDAwMDAwIiwicGhvbmVfbnVtYmVyIjoiNjAwMDAwMDAwMDAiLCJmdWxsX25hbWUiOiI2IiwiZW1haWwiOiI2QGV4YW1wbGUuY29tIiwic2NvcmUiOjQsImxhc3QtcXVlc3Rpb24taW50ZWdyYWwiOjEsImxhc3QtcXVlc3Rpb24tZGVyaXZhdGl2ZSI6MH0.zgwHcmLpaHqOxBdA5smcTcS_tMbXLzosZLx3MXY4mzs
###################################################



POST https://api.kavenegar.com/v1/2F727630526A427263695969303945455A4D515859584730792F715257615454654A2B58656D355A6E71633D/sms/send.json
Content-Type: application/json
Accept: application/json

{
  "message":"TEST",
  "sender": "2000660110" ,
  "receptor": "09352501923"
}
############################
https://api.kavenegar.com/v1/2F727630526A427263695969303945455A4D515859584730792F715257615454654A2B58656D355A6E71633D/sms/send.json?receptor=09999367495&sender=2000660110&message=test
########################


GET http://127.0.0.1:8000/question-web/
Content-Type: application/json
Accept: application/json
########################


GET http://127.0.0.1:8000/question-web/1/
Content-Type: application/json
Accept: application/json
########################
POST  http://127.0.0.1:8000/question-web/1/5/
Content-Type: application/json
Accept: application/json

{
  "answer":"1"
}
################3


GET http://77.237.82.221:8000/question-web/
Content-Type: application/json
Accept: application/json
############################33