POST http://127.0.0.1:8000/accounts/register/
Content-Type: application/json
Accept: application/json

{
  "email": "7@example.com",
  "phone_number": "70000000000",
  "full_name": "7",
  "password": "6541"
}


########
POST http://127.0.0.1:8000/accounts/verify/
Content-Type: application/json
Accept: application/json

{
  "code": 4299
}

#######
POST http://127.0.0.1:8000/accounts/login/
Content-Type: application/json
Accept: application/json

{
  "phone_number": "60000000000",
  "password":"6541"
}

##########
POST http://77.237.82.221:8000/accounts/login/
Content-Type: application/json
Accept: application/json

{
  "phone_number": "60000000000",
  "password":"6541"
}

###################################
GET  http://77.237.82.221:8000/question-app/15/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzIyNTM4LCJpYXQiOjE3NDUzMTY1MzgsImp0aSI6IjZiMzU4ZTY2ZTdkMDQ3NGVhZmI0ZmVlNjIyNjk1Y2MwIiwidXNlcl9pZCI6IjYwMDAwMDAwMDAwIiwicGhvbmVfbnVtYmVyIjoiNjAwMDAwMDAwMDAiLCJmdWxsX25hbWUiOiI2IiwiZW1haWwiOiI2QGV4YW1wbGUuY29tIiwic2NvcmUiOjIsImxhc3QtcXVlc3Rpb24taW50ZWdyYWwiOjEsImxhc3QtcXVlc3Rpb24tZGVyaXZhdGl2ZSI6MH0.D_7V3--Z496iUaL2Hh1qjlZ29YsnZu0Dh0C7WMSDlPo
####################################################################
GET  http://127.0.0.1:8000/question-app/15/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MzIyNTM4LCJpYXQiOjE3NDUzMTY1MzgsImp0aSI6IjZiMzU4ZTY2ZTdkMDQ3NGVhZmI0ZmVlNjIyNjk1Y2MwIiwidXNlcl9pZCI6IjYwMDAwMDAwMDAwIiwicGhvbmVfbnVtYmVyIjoiNjAwMDAwMDAwMDAiLCJmdWxsX25hbWUiOiI2IiwiZW1haWwiOiI2QGV4YW1wbGUuY29tIiwic2NvcmUiOjIsImxhc3QtcXVlc3Rpb24taW50ZWdyYWwiOjEsImxhc3QtcXVlc3Rpb24tZGVyaXZhdGl2ZSI6MH0.D_7V3--Z496iUaL2Hh1qjlZ29YsnZu0Dh0C7WMSDlPo
#################################




GET  http://127.0.0.1:8000/accounts/test/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTA2Mzc3LCJpYXQiOjE3NDQ5MDAzNzcsImp0aSI6IjRiNTc3N2NhNDg0NTQyM2U4YmI3MjFhNmY0YmY0ZjhmIiwidXNlcl9pZCI6IjYwMDAwMDAwMDAwIiwicGhvbmVfbnVtYmVyIjoiNjAwMDAwMDAwMDAiLCJmdWxsX25hbWUiOiI2IiwiZW1haWwiOiI2QGV4YW1wbGUuY29tIiwic2NvcmUiOjIsImxhc3QtcXVlc3Rpb24taW50ZWdyYWwiOjEsImxhc3QtcXVlc3Rpb24tZGVyaXZhdGl2ZSI6MH0.ml9mjJHTuWNTCQ720kVDKB7EzJtWGuK-G-jo5-j01G4
####################################
POST http://127.0.0.1:8000/question-app/13/ 
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTA2Mzc3LCJpYXQiOjE3NDQ5MDAzNzcsImp0aSI6IjRiNTc3N2NhNDg0NTQyM2U4YmI3MjFhNmY0YmY0ZjhmIiwidXNlcl9pZCI6IjYwMDAwMDAwMDAwIiwicGhvbmVfbnVtYmVyIjoiNjAwMDAwMDAwMDAiLCJmdWxsX25hbWUiOiI2IiwiZW1haWwiOiI2QGV4YW1wbGUuY29tIiwic2NvcmUiOjIsImxhc3QtcXVlc3Rpb24taW50ZWdyYWwiOjEsImxhc3QtcXVlc3Rpb24tZGVyaXZhdGl2ZSI6MH0.ml9mjJHTuWNTCQ720kVDKB7EzJtWGuK-G-jo5-j01G4
{
  "answer": "1"
}




###################################33

POST http://127.0.0.1:8000/accounts/token/
Content-Type: application/json
Accept: application/json

{
  "email": "7@example.com",
  "password": "6541"
}


######################################

POST http://127.0.0.1:8000/accounts/token/refresh/
Content-Type: application/json
Accept: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTkxOTY1NCwiaWF0IjoxNzQ1MzE0ODU0LCJqdGkiOiJjODQ1M2JmNzQxZDk0NjBlOTVlOTJjOTVkNmNhYmU5ZCIsInVzZXJfaWQiOiI3MDAwMDAwMDAwMCIsInBob25lX251bWJlciI6IjcwMDAwMDAwMDAwIiwiZnVsbF9uYW1lIjoiNyIsImVtYWlsIjoiN0BleGFtcGxlLmNvbSIsInNjb3JlIjowLCJsYXN0LXF1ZXN0aW9uLWludGVncmFsIjowLCJsYXN0LXF1ZXN0aW9uLWRlcml2YXRpdmUiOjB9.8vRXhW923J-72gODeo2YJTYHaUM6nJy3IUdCP5Y7gTA"
}


