# Generated by Django 4.2.11 on 2025-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_rename_img_base64_question_question_latex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stage',
            field=models.SmallIntegerField(null=True),
        ),
    ]
