# Generated by Django 4.2.11 on 2025-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_question_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
