# Generated by Django 4.2.11 on 2025-03-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_alter_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='solved_count',
        ),
    ]
