# Generated by Django 4.2.11 on 2025-03-22 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0022_category_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.category')),
                ('completed_questions', models.ManyToManyField(blank=True, related_name='completed_by_users', to='question.question')),
                ('last_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersolvedquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usersolvedquestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
        migrations.DeleteModel(
            name='UserSolvedQuestion',
        ),
    ]
