# Generated by Django 5.1.7 on 2025-03-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0024_userprogress_roadmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_questions',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='roadmap',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_question_orders',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_question',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
