# Generated by Django 5.2 on 2025-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0026_questionintegral_rename_question_questionderivative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionderivative',
            name='stage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
