# Generated by Django 5.2 on 2025-05-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0028_alter_questionintegral_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='last_question',
            new_name='last_question_derivative',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_question_orders',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_question_integral',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
